/**
 * Connaissances contextuelles : hiérarchie de thèmes et associations entre mots.
 */

/**
 * Thèmes qui ne disent rien du sujet du texte : ils décrivent une classe de
 * mots (verbes d'action, adjectifs de qualité…) et non un univers de sens.
 * Ils sont ignorés dans le calcul du contexte thématique.
 */
export const THEMES_NON_TOPIQUES = new Set([
  'outil', 'base', 'action', 'composé', 're', 'courant', 'qualité', 'état',
  'couleur', 'taille', 'manière', 'quantité', 'logique', 'temps', 'idée',
]);

/** thème → thèmes parents (un mot « fraise » active aussi « nourriture », « nature »…). */
export const PARENTS_THEMES: Record<string, string[]> = {
  fruit: ['nourriture', 'nature'],
  légume: ['nourriture', 'nature', 'jardin'],
  boisson: ['nourriture'],
  repas: ['nourriture', 'maison'],
  animal: ['nature'],
  famille: ['personne'],
  métier: ['personne', 'travail'],
  corps: ['personne', 'santé'],
  santé: ['corps'],
  émotion: ['personne'],
  école: ['travail', 'lecture'],
  matière: ['école'],
  nombre: ['école'],
  forme: ['école'],
  meuble: ['maison', 'objet'],
  jeu: ['loisir'],
  sport: ['loisir', 'corps'],
  musique: ['art', 'loisir'],
  art: ['loisir'],
  ville: ['lieu'],
  transport: ['ville', 'voyage'],
  météo: ['nature', 'temps'],
  saison: ['temps', 'nature'],
  espace: ['nature'],
  sortie: ['loisir', 'voyage'],
  vêtement: ['objet'],
  jardin: ['maison', 'nature'],
};

/**
 * Associations « mot précédent → mots probables ensuite ».
 * Sert à la fois à proposer le mot suivant (avant même la première lettre)
 * et à faire remonter les bons candidats dès la première lettre tapée.
 */
export const BIGRAMMES: Record<string, string> = {
  je: 'suis ai vais veux peux dois sais crois pense vois fais mange joue vais aime',
  "j'": 'ai aime adore arrive écoute habite essaie ouvre entends imagine',
  tu: 'es as vas veux peux dois sais fais viens joues manges aimes',
  il: 'est a va veut peut doit fait dit vient y était faut',
  elle: 'est a va veut peut doit fait dit vient était',
  on: 'est a va peut doit fait dit part joue mange',
  nous: 'sommes avons allons voulons pouvons devons faisons partons jouons',
  vous: 'êtes avez allez voulez pouvez devez faites partez',
  ils: 'sont ont vont veulent peuvent doivent font disent viennent étaient',
  elles: 'sont ont vont veulent peuvent doivent font sont',
  "c'": 'est était',
  ce: 'est était soir matin sont',
  'il y': 'a avait aura',
  je_suis: 'content allé parti heureux triste fatigué',
  est: 'très un une le la beau grand petit content arrivé parti allé',
  était: 'très un une le la beau grand petit content une fois',
  sont: 'très des les beaux grands petits contents arrivés partis',
  ai: 'un une des mangé vu fait pris trouvé dit mal peur envie besoin faim soif',
  as: 'un une des mangé vu fait pris trouvé raison tort',
  a: 'un une des mangé vu fait pris dit trouvé mal peur envie besoin',
  avons: 'un une des mangé vu fait vus trouvé',
  ont: 'un des mangé vu fait trouvé',
  très: 'beau belle bien grand petit content heureux joli bon gentil fort vite important difficile',
  trop: 'grand petit chaud froid tard tôt fort vite de bien',
  assez: 'grand de bien fort',
  plus: 'de grand tard tôt loin vite fort en',
  moins: 'de en',
  beaucoup: 'de trop plus',
  peu: 'de plus après',
  un: 'peu petit grand gros autre bon beau joli jour',
  une: 'petite grande autre belle bonne jolie fois',
  le: 'petit grand plus même seul jour soir matin monde',
  la: 'petite grande plus même première',
  les: 'petits grandes grands autres mêmes premiers',
  des: 'petits grandes grands autres',
  mon: 'petit grand cher',
  ma: 'petite grande chère',
  mes: 'petits grands',
  dans: 'la le les mon ma mes un une son sa ses cette ce',
  sur: 'la le les mon ma un une son sa ses cette table lit',
  sous: 'la le les mon un une son sa ses',
  avec: 'mon ma mes un une le la les son sa ses toi moi lui elle nous eux',
  pour: 'la le les moi toi lui aller faire voir que mon ma mes un une',
  chez: 'moi toi lui elle nous vous eux mon ma mes le la',
  de: 'la le les mon ma mes son sa ses temps plus rien tout façon',
  à: 'la le les mon ma mes côté cause peine nouveau droite gauche travers midi',
  au: 'bord milieu revoir lieu moins fond début début courant',
  en: 'train plus classe bas haut avant face effet même France ville forme',
  'est-ce': 'que',
  parce: 'que',
  quelque: 'chose fois part',
  tout: 'le la les de suite à coup droit seul petit doucement',
  tous: 'les des',
  toute: 'la une seule',
  toutes: 'les des',
  y: 'a avait aura est',
  ne: 'pas plus jamais rien veux peux sais suis vais',
  pas: 'de le la les encore très beaucoup mal du',
  bien: 'sûr que plus fait aimé',
  faire: 'un une du de la attention plaisir les le la',
  aller: 'à au chez en dans se voir chercher',
  vais: 'aller faire voir manger jouer partir prendre à au chez',
  veux: 'aller faire voir manger jouer partir prendre pas bien',
  peux: 'aller faire voir venir prendre pas',
  faut: 'que aller faire prendre pas bien',
  avoir: 'un une des peur mal faim soif envie besoin',
  être: 'un une très content triste heureux malade prêt',
  quand: 'je tu il elle on nous vous ils même',
  si: 'je tu il elle on tu beau grand bien content',
  comme: 'un une le la ça moi toi il',
  mais: 'je il elle on nous ce je vais aussi',
  et: 'je il elle on nous puis après ensuite le la les un une',
  ou: 'le la les un une bien',
  donc: 'je il elle on nous',
  alors: 'je il elle on nous que',
  puis: 'je il elle on nous après',
  ensuite: 'je il elle on nous',
  aujourd_hui: 'je il nous on',
  maintenant: 'je il elle on que',
  hier: 'je il elle on nous',
  demain: 'je il elle on nous',
  après: 'le la les midi avoir être manger',
  avant: 'le la les de que d\'aller',
  pendant: 'le la les que',
  jour: 'de la le où',
  fois: 'par que de',
  aime: 'beaucoup bien les le la mon ma manger jouer aller lire',
  aimes: 'beaucoup bien les le la ton ta',
  adore: 'les le la mon ma manger jouer',
  déteste: 'les le la manger',
  manger: 'des du de la un une les',
  boire: 'de du un une',
  jouer: 'avec au à dans dehors',
  regarder: 'la le les un une',
  écouter: 'la le les de',
  lire: 'un une le la des',
  écrire: 'un une le la des',
  prendre: 'un une le la des mon ma',
  mettre: 'un une le la des mon ma',
  donner: 'un une le la des mon ma',
  voir: 'un une le la des mon ma',
  partir: 'à au en chez avec',
  monter: 'dans sur à',
  descendre: 'de dans du',
  arriver: 'à au en chez',
  fruits: 'frais rouges mûrs et',
  légumes: 'verts frais et',
  animaux: 'sauvages de la domestiques',
  enfants: 'de la et jouent sont ont',
  histoire: 'de la du qui était',
  livre: 'de sur qui est',
  maison: 'de mon ma est où',
  école: 'de ma mon est primaire',
  matin: 'je il elle on nous',
  soir: 'je il elle on nous',
  été: 'très bien content malade dernier',
  fait: 'beau chaud froid un une des très mal',
};

/**
 * Groupes de mots qui « vont ensemble » : si l\'un apparaît dans le texte,
 * les autres remontent dans les propositions même sans thème commun.
 */
export const ASSOCIATIONS: string[][] = [
  ['fruit', 'fruits', 'pomme', 'poire', 'fraise', 'framboise', 'cerise', 'banane', 'orange', 'raisin', 'abricot', 'pêche', 'melon', 'prune', 'kiwi', 'ananas', 'mûre', 'myrtille', 'figue', 'mangue', 'clémentine', 'panier', 'jus', 'confiture', 'tarte', 'sucré', 'mûr', 'juteux', 'manger', 'goûter', 'cueillir', 'vitamine', 'dessert', 'saladier'],
  ['légume', 'légumes', 'carotte', 'tomate', 'salade', 'courgette', 'haricot', 'poireau', 'épinard', 'potager', 'soupe', 'purée', 'cuire', 'jardin'],
  ['école', 'classe', 'maîtresse', 'maître', 'élève', 'cartable', 'cahier', 'stylo', 'crayon', 'trousse', 'récréation', 'devoirs', 'leçon', 'tableau', 'bureau', 'copain', 'copine', 'cour', 'cantine', 'apprendre', 'écrire', 'lire', 'compter', 'dictée'],
  ['plage', 'mer', 'sable', 'vague', 'coquillage', 'château', 'maillot', 'nager', 'bronzer', 'parasol', 'crabe', 'bateau', 'soleil', 'vacances', 'serviette', 'seau', 'pelle', 'île'],
  ['forêt', 'arbre', 'feuille', 'branche', 'champignon', 'écureuil', 'renard', 'cerf', 'sanglier', 'sentier', 'promenade', 'cabane', 'mousse', 'oiseau', 'nid', 'bois'],
  ['neige', 'hiver', 'froid', 'flocon', 'bonhomme', 'luge', 'ski', 'glace', 'gants', 'bonnet', 'écharpe', 'manteau', 'sapin', 'Noël', 'chocolat chaud', 'geler', 'glisser'],
  ['anniversaire', 'gâteau', 'bougie', 'cadeau', 'invité', 'fête', 'ballon', 'jeu', 'bonbon', 'surprise', 'chanter', 'souffler', 'décoration'],
  ['chien', 'chat', 'animal', 'niche', 'os', 'croquette', 'promener', 'aboyer', 'miauler', 'patte', 'poil', 'queue', 'laisse', 'vétérinaire', 'caresser'],
  ['football', 'ballon', 'but', 'équipe', 'joueur', 'match', 'stade', 'terrain', 'gagner', 'perdre', 'marquer', 'arbitre', 'maillot', 'entraînement'],
  ['maison', 'chambre', 'cuisine', 'salon', 'jardin', 'porte', 'fenêtre', 'lit', 'table', 'escalier', 'clé', 'toit', 'mur'],
  ['voiture', 'route', 'rouler', 'conduire', 'ceinture', 'garage', 'essence', 'pneu', 'voyage', 'embouteillage', 'klaxon'],
  ['médecin', 'malade', 'fièvre', 'rhume', 'médicament', 'hôpital', 'piqûre', 'pansement', 'guérir', 'tousser', 'lit', 'docteur'],
  ['montagne', 'randonnée', 'sommet', 'sentier', 'rocher', 'refuge', 'ski', 'chalet', 'vallée', 'grimper', 'sac à dos'],
  ['ordinateur', 'écran', 'clavier', 'souris', 'internet', 'jeu', 'taper', 'cliquer', 'enregistrer', 'tablette', 'vidéo'],
  ['pirate', 'bateau', 'trésor', 'île', 'carte', 'perroquet', 'sabre', 'coffre', 'mer', 'capitaine', 'aventure'],
  ['dragon', 'château', 'chevalier', 'princesse', 'roi', 'reine', 'magie', 'sorcière', 'épée', 'conte', 'royaume', 'fée'],
];
