/**
 * Noms communs du vocabulaire d\'un enfant (cycle 2 / cycle 3).
 *
 * Format compact : [thème, fréquence (1 = rare … 5 = très fréquent), "entrées"]
 * Une entrée = "mot:genre[:emoji][:pluriel irrégulier]"
 *   genre : m | f | mf
 *   Le pluriel régulier est calculé automatiquement (voir flexion.ts).
 *   Le « : » final sert à sauter un champ, ex. "bras:m::bras".
 */
export const NOMS: [theme: string, freq: number, entries: string][] = [
  // ─── Compléments du quotidien ──────────────────────────────────────────
  ['animal', 4, 'croquette:f:🦴 laisse:f:🦮 gamelle:f:🥣 collier:m:🦮 poil:m:🐾 plume:f:🪶 corne:f:🐂 griffe:f:🐾 bec:m:🐦 nageoire:f:🐟 coquille:f:🐚 coquillage:m:🐚 terrier:m:🕳️ tanière:f:🕳️ troupeau:m:🐑'],
  ['jeu', 4, 'cachette:f:🙈 cache-cache:m:🙈 marelle:f:🔢 dînette:f:🍽️ dominos:m:🀄 cerceau:m:⭕ quille:f:🎳 osselet:m:🦴 élastique:m:➰ craie:f:🖍️ trésor:m:💎 équipe:f:👥 tour:m:🔄 gage:m:🎲 devinette:f:❓ blague:f:😂 farce:f:🤪'],
  ['nourriture', 4, 'gaufre:f:🧇 brioche:f:🥐 pain au chocolat:m:🥐 chausson:m:🥟 chips:f:🍟 pop-corn:m:🍿 hamburger:m:🍔 quiche:f:🥧 gratin:m:🧀 omelette:f:🍳 sandwich:m:🥪 barquette:f:🍓 goûter:m:🍪 miette:f:🍞 croûte:f:🍞 mie:f:🍞 tranche:f:🍞 morceau:m:🍰 part:f:🍰'],
  ['objet', 4, 'mouchoir:m:🤧 pansement:m:🩹 élastique:m:➰ barrette:f:💇 parapluie:m:☂️ bouée:f:🛟 masque:m:🤿 palme:f:🤿 lampe de poche:f:🔦 boussole:f:🧭 jumelles:f:🔭 loupe:f:🔍 aimant:m:🧲 ficelle:f:🧵 scotch:m:📏 trombone:m:📎 agrafe:f:📎 punaise:f:📌 carnet:m:📓 calendrier:m:📅'],
  ['émotion', 4, 'chatouille:f:😆 grimace:f:😜 punition:f:😤 récompense:f:🏅 promesse:f:🤝 excuse:f:🙏 compliment:m:💐 souci:m:😟 espoir:m:🤞 confiance:f:🤝 patience:f:⏳ fierté:f:😌 gentillesse:f:😇 méchanceté:f:😈'],
  // ─── Nourriture ────────────────────────────────────────────────────────
  ['fruit', 4, 'fruit:m:🍎 pomme:f:🍎 poire:f:🍐 banane:f:🍌 fraise:f:🍓 framboise:f:🫐 cerise:f:🍒 orange:f:🍊 citron:m:🍋 raisin:m:🍇 pêche:f:🍑 abricot:m:🍑 prune:f:🟣 melon:m:🍈 pastèque:f:🍉 ananas:m:🍍 kiwi:m:🥝 mangue:f:🥭 noix:f:🌰: myrtille:f:🫐 mûre:f:🫐 groseille:f:🔴 clémentine:f:🍊 mandarine:f:🍊 pamplemousse:m:🍊 figue:f:🟤 datte:f:🟤 noisette:f:🌰 amande:f:🌰 châtaigne:f:🌰 marron:m:🌰 olive:f:🫒 coco:f:🥥'],
  ['légume', 4, 'légume:m:🥕 carotte:f:🥕 tomate:f:🍅 salade:f:🥗 pomme de terre:f:🥔 patate:f:🥔 haricot:m:🫘 petit pois:m:🫛 courgette:f:🥒 concombre:m:🥒 aubergine:f:🍆 poivron:m:🫑 oignon:m:🧅 ail:m:🧄 champignon:m:🍄 chou:m:🥬 chou-fleur:m:🥦 brocoli:m:🥦 épinard:m:🥬 navet:m:🥔 radis:m:🔴 poireau:m:🥬 betterave:f:🔴 citrouille:f:🎃 potiron:m:🎃 maïs:m:🌽 lentille:f:🫘'],
  ['nourriture', 5, 'pain:m:🍞 baguette:f:🥖 croissant:m:🥐 gâteau:m:🍰 tarte:f:🥧 crêpe:f:🥞 biscuit:m:🍪 bonbon:m:🍬 chocolat:m:🍫 glace:f:🍦 sucre:m:🧂 sel:m:🧂 poivre:m:🧂 beurre:m:🧈 fromage:m:🧀 œuf:m:🥚 lait:m:🥛 yaourt:m:🥛 confiture:f:🍯 miel:m:🍯 farine:f:🌾 riz:m:🍚 pâtes:f:🍝 pizza:f:🍕 sandwich:m:🥪 frite:f:🍟 soupe:f:🍲 purée:f:🥔 salade:f:🥗 viande:f:🥩 poulet:m:🍗 jambon:m:🥓 saucisse:f:🌭 steak:m:🥩 poisson:m:🐟 crevette:f:🦐 sauce:f:🥫 huile:f:🫒 vinaigre:m:🍾 moutarde:f:🌭 ketchup:m:🍅 céréale:f:🥣 miettes:f:🍞 goûter:m:🍪 dessert:m:🍰 bonbons:m:🍬 sirop:m:🍯 crème:f:🍨 mousse:f:🍮 pâte:f:🥟 sucrerie:f:🍬'],
  ['boisson', 4, 'boisson:f:🥤 eau:f:💧 jus:m:🧃: lait:m:🥛 café:m:☕ thé:m:🍵 tisane:f:🍵 chocolat chaud:m:☕ limonade:f:🥤 soda:m:🥤 grenadine:f:🍹 bouteille:f:🍾 verre:m:🥛 gourde:f:🧴 canette:f:🥤'],
  ['repas', 4, 'repas:m:🍽️: petit-déjeuner:m:🥐 déjeuner:m:🍽️ dîner:m:🍽️ souper:m:🍽️ cantine:f:🍽️ pique-nique:m:🧺 recette:f:📖 menu:m:📋 assiette:f:🍽️ fourchette:f:🍴 couteau:m:🔪 cuillère:f:🥄 bol:m:🥣 tasse:f:☕ plat:m:🍲 nappe:f:🧻 serviette:f:🧻 casserole:f:🍲 poêle:f:🍳 four:m:🔥 marmite:f:🍲'],

  // ─── Animaux ───────────────────────────────────────────────────────────
  ['animal', 5, 'animal:m:🐾:animaux chien:m:🐶 chat:m:🐱 chatte:f:🐱 chiot:m:🐶 chaton:m:🐱 lapin:m:🐰 hamster:m:🐹 souris:f:🐭: poisson:m:🐟 oiseau:m:🐦 tortue:f:🐢 serpent:m:🐍 grenouille:f:🐸 escargot:m:🐌 ver:m:🪱 araignée:f:🕷️ fourmi:f:🐜 abeille:f:🐝 guêpe:f:🐝 papillon:m:🦋 coccinelle:f:🐞 mouche:f:🪰 moustique:m:🦟 libellule:f:🪰 chenille:f:🐛 insecte:m:🐛 crabe:m:🦀 poule:f:🐔 coq:m:🐓 poussin:m:🐤 canard:m:🦆 oie:f:🦢 dinde:f:🦃 vache:f:🐮 taureau:m:🐂 veau:m:🐄 cochon:m:🐷 mouton:m:🐑 agneau:m:🐑 chèvre:f:🐐 cheval:m:🐴:chevaux poney:m:🐴 âne:m:🫏 lion:m:🦁 lionne:f:🦁 tigre:m:🐯 ours:m:🐻: loup:m:🐺 renard:m:🦊 cerf:m:🦌 biche:f:🦌 sanglier:m:🐗 écureuil:m:🐿️ hérisson:m:🦔 taupe:f:🐁 chauve-souris:f:🦇 singe:m:🐵 gorille:m:🦍 éléphant:m:🐘 girafe:f:🦒 zèbre:m:🦓 hippopotame:m:🦛 rhinocéros:m:🦏: crocodile:m:🐊 kangourou:m:🦘 koala:m:🐨 panda:m:🐼 pingouin:m:🐧 manchot:m:🐧 phoque:m:🦭 dauphin:m:🐬 baleine:f:🐋 requin:m:🦈 pieuvre:f:🐙 poulpe:m:🐙 méduse:f:🪼 étoile de mer:f:⭐ hibou:m:🦉 chouette:f:🦉 aigle:m:🦅 corbeau:m:🐦‍⬛ pigeon:m:🐦 moineau:m:🐦 mésange:f:🐦 hirondelle:f:🐦 perroquet:m:🦜 paon:m:🦚 cygne:m:🦢 flamant:m:🦩 dragon:m:🐉 dinosaure:m:🦕 licorne:f:🦄 nid:m:🪹 plume:f:🪶 patte:f:🐾 queue:f:🐾 aile:f:🪽 museau:m:🐽 poil:m:🐾 laine:f:🧶 ruche:f:🐝 niche:f:🏠 cage:f:🪤 aquarium:m:🐠 zoo:m:🦁 ferme:f:🚜'],

  // ─── Famille & personnes ───────────────────────────────────────────────
  ['famille', 5, 'famille:f:👨‍👩‍👧 maman:f:👩 papa:m:👨 mère:f:👩 père:m:👨 parent:m:👪 frère:m:👦 sœur:f:👧 bébé:m:👶 enfant:mf:🧒 fille:f:👧 garçon:m:👦 mamie:f:👵 papi:m:👴 grand-mère:f:👵 grand-père:m:👴 grands-parents:m:👴 tante:f:👩 oncle:m:👨 cousin:m:👦 cousine:f:👧 neveu:m:👦 nièce:f:👧 jumeau:m:👯 jumelle:f:👯 mariage:m:💒 anniversaire:m:🎂'],
  ['personne', 5, 'personne:f:🧑 gens:m:👥 monsieur:m:👨:messieurs madame:f:👩:mesdames ami:m:🧑‍🤝‍🧑 amie:f:👭 copain:m:🧑‍🤝‍🧑 copine:f:👭 camarade:mf:🧑‍🤝‍🧑 voisin:m:🏠 voisine:f:🏠 homme:m:👨 femme:f:👩 adulte:mf:🧑 jeune:mf:🧑 élève:mf:🎒 enfants:m:🧒 invité:m:🎉 héros:m:🦸: héroïne:f:🦸‍♀️ géant:m:🧌 sorcière:f:🧙‍♀️ sorcier:m:🧙 fée:f:🧚 prince:m:🤴 princesse:f:👸 roi:m:🤴 reine:f:👸 chevalier:m:⚔️ pirate:m:🏴‍☠️ clown:m:🤡 monstre:m:👹 fantôme:m:👻 robot:m:🤖 nain:m:🧙 lutin:m:🧝'],
  ['métier', 3, 'métier:m:🧰 maître:m:👨‍🏫 maîtresse:f:👩‍🏫 professeur:m:👨‍🏫 instituteur:m:👨‍🏫 institutrice:f:👩‍🏫 directeur:m:👔 directrice:f:👔 docteur:m:👨‍⚕️ médecin:m:👨‍⚕️ infirmier:m:👨‍⚕️ infirmière:f:👩‍⚕️ dentiste:mf:🦷 pompier:m:🧑‍🚒 policier:m:👮 gendarme:m:👮 facteur:m:📮 boulanger:m:🥖 boulangère:f:🥖 pâtissier:m:🧁 boucher:m:🥩 cuisinier:m:👨‍🍳 serveur:m:🍽️ vendeur:m:🛍️ vendeuse:f:🛍️ coiffeur:m:💇 fermier:m:🧑‍🌾 agriculteur:m:🚜 jardinier:m:🌱 peintre:mf:🎨 artiste:mf:🎨 chanteur:m:🎤 chanteuse:f:🎤 musicien:m:🎺 danseur:m:🩰 danseuse:f:🩰 acteur:m:🎭 actrice:f:🎭 écrivain:m:✍️ auteur:m:✍️ journaliste:mf:📰 photographe:mf:📷 pilote:m:✈️ chauffeur:m:🚌 conducteur:m:🚗 mécanicien:m:🔧 plombier:m:🔧 menuisier:m:🪚 maçon:m:🧱 astronaute:mf:👨‍🚀 scientifique:mf:🔬 vétérinaire:mf:🐕 bibliothécaire:mf:📚 sportif:m:⚽ footballeur:m:⚽ pêcheur:m:🎣 marin:m:⚓ soldat:m:🪖 juge:m:⚖️ avocat:m:⚖️ caissière:f:🛒 informaticien:m:💻'],
  ['corps', 4, 'corps:m:🧍: tête:f:🗣️ cheveu:m:💇 visage:m:😀 front:m:😀 œil:m:👁️:yeux oreille:f:👂 nez:m:👃: bouche:f:👄 lèvre:f:👄 dent:f:🦷 langue:f:👅 joue:f:😊 menton:m:😀 cou:m:🧣 épaule:f:💪 bras:m:💪: coude:m:💪 main:f:✋ doigt:m:👆 pouce:m:👍 ongle:m:💅 poitrine:f:🫁 ventre:m:🤰 dos:m:🔙: jambe:f:🦵 genou:m:🦵 pied:m:🦶 orteil:m:🦶 cheville:f:🦶 peau:f:🫲 cœur:m:❤️ sang:m:🩸 os:m:🦴 muscle:m:💪 cerveau:m:🧠 voix:f:🗣️ larme:f:😢 sourire:m:😊'],
  ['santé', 3, 'santé:f:💊 maladie:f:🤒 rhume:m:🤧 fièvre:f:🌡️ toux:f:😷: grippe:f:🤒 douleur:f:😖 blessure:f:🩹 bobo:m:🩹 bleu:m:🩹 pansement:m:🩹 médicament:m:💊 sirop:m:💊 piqûre:f:💉 vaccin:m:💉 hôpital:m:🏥:hôpitaux cabinet:m:🩺 ordonnance:f:📄 allergie:f:🤧 lunettes:f:👓 fatigue:f:😴 sommeil:m:😴 rêve:m:💭 cauchemar:m:😱'],
  ['émotion', 4, 'joie:f:😄 bonheur:m:😄 tristesse:f:😢 colère:f:😠 peur:f:😨 surprise:f:😲 honte:f:😳 jalousie:f:😒 amour:m:❤️ amitié:f:🤝 courage:m:🦁 fierté:f:😌 envie:f:🤩 ennui:m:😑 stress:m:😰 calme:m:😌 humeur:f:🙂 sentiment:m:💗 émotion:f:💗 rire:m:😂 cri:m:😱 câlin:m:🤗 bisou:m:😘 secret:m:🤫 mensonge:m:🤥 bêtise:f:🙃 caprice:m:😤 dispute:f:😠'],

  // ─── École ─────────────────────────────────────────────────────────────
  ['école', 5, 'école:f:🏫 classe:f:🏫 cours:m:📚: leçon:f:📖 devoir:m:📝 exercice:m:✏️ récréation:f:🤸 récré:f:🤸 cantine:f:🍽️ cartable:m:🎒 sac:m:🎒 trousse:f:✏️ cahier:m:📓 livre:m:📕 manuel:m:📘 classeur:m:🗂️ feuille:f:📄 page:f:📄 stylo:m:🖊️ crayon:m:✏️ gomme:f:🧽 règle:f:📏 ciseaux:m:✂️ colle:f:🩹 taille-crayon:m:✏️ feutre:m:🖍️ craie:f:🖍️ ardoise:f:📝 tableau:m:🖼️ bureau:m:🪑 chaise:f:🪑 casier:m:🗄️ agenda:m:📅 dictionnaire:m:📚 bibliothèque:f:📚 maternelle:f:🧸 collège:m:🏫 lycée:m:🏫 université:f:🎓 maîtresse:f:👩‍🏫 devoirs:m:📝 note:f:💯 contrôle:m:📝 évaluation:f:📝 dictée:f:✍️ rédaction:f:✍️ calcul:m:🔢 lecture:f:📖 écriture:f:✍️ orthographe:f:🔤 grammaire:f:🔤 conjugaison:f:🔤 vocabulaire:m:🔤 mot:m:🔤 lettre:f:🔤 phrase:f:📝 texte:m:📄 histoire:f:📖 poème:m:📜 titre:m:🏷️ question:f:❓ réponse:f:💬 erreur:f:❌ faute:f:❌ progrès:m:📈: effort:m:💪 récompense:f:🏅 sortie:f:🚌 voyage scolaire:m:🚌 rentrée:f:🎒 vacances:f:🏖️'],
  ['matière', 3, 'français:m:🇫🇷: mathématiques:f:🔢 maths:f:🔢 histoire:f:🏛️ géographie:f:🌍 sciences:f:🔬 anglais:m:🇬🇧: musique:f:🎵 sport:m:⚽ dessin:m:🎨 arts plastiques:m:🎨 informatique:f:💻 technologie:f:⚙️'],
  ['nombre', 4, 'nombre:m:🔢 chiffre:m:🔢 numéro:m:🔢 addition:f:➕ soustraction:f:➖ multiplication:f:✖️ division:f:➗ résultat:m:🟰 total:m:🟰:totaux moitié:f:½ quart:m:¼ double:m:✖️ paire:f:👯 dizaine:f:🔟 centaine:f:💯 millier:m:🔢 million:m:🔢 mesure:f:📏 mètre:m:📏 centimètre:m:📏 kilomètre:m:📏 gramme:m:⚖️ kilo:m:⚖️ litre:m:🧴 degré:m:🌡️ euro:m:💶 centime:m:🪙 argent:m:💰 pièce:f:🪙 billet:m:💵 prix:m:🏷️: monnaie:f:🪙'],
  ['forme', 3, 'forme:f:⬜ carré:m:⬜ rectangle:m:▭ triangle:m:🔺 cercle:m:⭕ rond:m:⭕ ovale:m:🥚 losange:m:🔷 étoile:f:⭐ cube:m:🧊 boule:f:⚪ ligne:f:➖ trait:m:➖ point:m:⏺️: courbe:f:〰️ croix:f:✝️ flèche:f:➡️ angle:m:📐 côté:m:📐 milieu:m:🎯 bord:m:📏'],

  // ─── Maison ────────────────────────────────────────────────────────────
  ['maison', 5, 'maison:f:🏠 appartement:m:🏢 immeuble:m:🏢 chambre:f:🛏️ cuisine:f:🍳 salon:m:🛋️ salle de bain:f:🛁 salle à manger:f:🍽️ toilettes:f:🚽 couloir:m:🚪 escalier:m:🪜 grenier:m:📦 cave:f:📦 garage:m:🚗 jardin:m:🌳 balcon:m:🪴 terrasse:f:🪴 cour:f:🏡 porte:f:🚪 fenêtre:f:🪟 mur:m:🧱 toit:m:🏠 plafond:m:⬆️ sol:m:⬇️ cheminée:f:🔥 clé:f:🔑 sonnette:f:🔔 boîte aux lettres:f:📮 adresse:f:📍 étage:m:🏢 ascenseur:m:🛗 pièce:f:🚪 cabane:f:🛖 tente:f:⛺ château:m:🏰:châteaux'],
  ['meuble', 4, 'meuble:m:🪑 lit:m:🛏️ table:f:🪑 chaise:f:🪑 fauteuil:m:🛋️ canapé:m:🛋️ armoire:f:🚪 placard:m:🚪 étagère:f:📚 tiroir:m:🗄️ commode:f:🗄️ bureau:m:🪑 miroir:m:🪞 tapis:m:🧶: rideau:m:🪟 lampe:f:💡 coussin:m:🛋️ couverture:f:🛏️ drap:m:🛏️ oreiller:m:🛏️ matelas:m:🛏️ tabouret:m:🪑 berceau:m:👶'],
  ['objet', 5, 'objet:m:📦 chose:f:📦 truc:m:📦 boîte:f:📦 sac:m:👜 valise:f:🧳 panier:m:🧺 carton:m:📦 papier:m:📄 journal:m:📰:journaux magazine:m:📖 photo:f:📷 tableau:m:🖼️ cadre:m:🖼️ horloge:f:🕐 montre:f:⌚ réveil:m:⏰ téléphone:m:📱 portable:m:📱 ordinateur:m:💻 tablette:f:📱 télévision:f:📺 télé:f:📺 radio:f:📻 casque:m:🎧 écran:m:🖥️ clavier:m:⌨️ souris:f:🖱️: appareil:m:📷 machine:f:⚙️ outil:m:🔧 marteau:m:🔨 tournevis:m:🪛: clou:m:📌 vis:f:🪛: échelle:f:🪜 corde:f:🪢 ficelle:f:🧵 fil:m:🧵 aiguille:f:🪡 bouton:m:🔘 pile:f:🔋 ampoule:f:💡 bougie:f:🕯️ allumette:f:🔥 balai:m:🧹 poubelle:f:🗑️ seau:m:🪣 éponge:f:🧽 savon:m:🧼 brosse:f:🪥 brosse à dents:f:🪥 dentifrice:m:🦷 peigne:m:💇 serviette:f:🧺 douche:f:🚿 baignoire:f:🛁 robinet:m:🚰 parapluie:m:☂️ lunettes:f:👓 sac à dos:m:🎒 portefeuille:m:👛 cadeau:m:🎁 ballon:m:🎈 bouteille:f:🍾 pot:m:🏺 vase:m:🏺 clef:f:🔑 carte:f:🗺️ ticket:m:🎫 billet:m:🎟️ enveloppe:f:✉️ lettre:f:✉️ timbre:m:📮 colis:m:📦: étiquette:f:🏷️'],

  // ─── Nature ────────────────────────────────────────────────────────────
  ['nature', 5, 'nature:f:🌿 arbre:m:🌳 feuille:f:🍃 branche:f:🌿 tronc:m:🪵 racine:f:🌱 fleur:f:🌸 rose:f:🌹 tulipe:f:🌷 marguerite:f:🌼 tournesol:m:🌻 pâquerette:f:🌼 coquelicot:m:🌺 herbe:f:🌿 gazon:m:🌱 pelouse:f:🌱 buisson:m:🌳 haie:f:🌳 forêt:f:🌲 bois:m:🌲: champ:m:🌾 prairie:f:🌾 montagne:f:⛰️ colline:f:⛰️ vallée:f:🏞️ rocher:m:🪨 pierre:f:🪨 caillou:m:🪨 sable:m:🏖️ terre:f:🌍 boue:f:🟤 poussière:f:💨 rivière:f:🏞️ fleuve:m:🏞️ ruisseau:m:💧 lac:m:🏞️ étang:m:🦆 mer:f:🌊 océan:m:🌊 plage:f:🏖️ vague:f:🌊 île:f:🏝️ falaise:f:🪨 grotte:f:🕳️ volcan:m:🌋 désert:m:🏜️ jungle:f:🌴 cascade:f:💦 sapin:m:🌲 chêne:m:🌳 pommier:m:🍎 palmier:m:🌴 cactus:m:🌵: graine:f:🌱 plante:f:🪴 mousse:f:🌿 champignon:m:🍄 papillon:m:🦋 nid:m:🪹'],
  ['météo', 4, 'temps:m:🌤️: météo:f:🌤️ soleil:m:☀️ nuage:m:☁️ pluie:f:🌧️ vent:m:💨 orage:m:⛈️ éclair:m:⚡ tonnerre:m:🌩️ neige:f:❄️ flocon:m:❄️ glace:f:🧊 grêle:f:🌨️ brouillard:m:🌫️ tempête:f:🌪️ arc-en-ciel:m:🌈 chaleur:f:🥵 froid:m:🥶 gel:m:🧊 ombre:f:🌂 lumière:f:💡 goutte:f:💧 flaque:f:💧 ciel:m:🌌:cieux'],
  ['espace', 3, 'espace:m:🚀 ciel:m:🌌 étoile:f:⭐ lune:f:🌙 soleil:m:☀️ planète:f:🪐 terre:f:🌍 mars:f:🔴: fusée:f:🚀 navette:f:🚀 satellite:m:🛰️ comète:f:☄️ galaxie:f:🌌 univers:m:🌌: astronaute:mf:👨‍🚀 télescope:m:🔭 extraterrestre:m:👽 soucoupe:f:🛸'],
  ['saison', 4, 'saison:f:🍂 printemps:m:🌸 été:m:☀️ automne:m:🍂 hiver:m:❄️ année:f:📅 mois:m:📅: semaine:f:📅 jour:m:📅 journée:f:📅 matin:m:🌅 matinée:f:🌅 midi:m:🕛 après-midi:m:🌤️ soir:m:🌆 soirée:f:🌆 nuit:f:🌙 minuit:m:🕛 heure:f:🕐 minute:f:⏱️ seconde:f:⏱️ moment:m:⏳ instant:m:⏳ aujourd\'hui:m:📅 demain:m:📅 hier:m:📅 date:f:📅 calendrier:m:📅 lundi:m:📅 mardi:m:📅 mercredi:m:📅 jeudi:m:📅 vendredi:m:📅 samedi:m:📅 dimanche:m:📅 janvier:m:📅 février:m:📅 mars:m:📅: avril:m:📅 mai:m:📅 juin:m:📅 juillet:m:📅 août:m:📅: septembre:m:📅 octobre:m:📅 novembre:m:📅 décembre:m:📅 fête:f:🎉 Noël:m:🎄 Pâques:f:🐣 carnaval:m:🎭 Halloween:f:🎃 vacances:f:🏖️ week-end:m:🎉'],

  // ─── Ville & transports ────────────────────────────────────────────────
  ['ville', 4, 'ville:f:🏙️ village:m:🏘️ rue:f:🛣️ route:f:🛣️ chemin:m:🛤️ avenue:f:🛣️ place:f:⛲ trottoir:m:🚶 pont:m:🌉 quartier:m:🏘️ centre:m:🏙️ magasin:m:🏬 boutique:f:🛍️ supermarché:m:🛒 marché:m:🧺 boulangerie:f:🥖 pharmacie:f:💊 librairie:f:📚 banque:f:🏦 poste:f:📮 mairie:f:🏛️ église:f:⛪ musée:m:🏛️ cinéma:m:🎬 théâtre:m:🎭 piscine:f:🏊 stade:m:🏟️ gare:f:🚉 aéroport:m:✈️ hôtel:m:🏨 restaurant:m:🍽️ café:m:☕ parc:m:🌳 square:m:🌳 zoo:m:🦁 hôpital:m:🏥:hôpitaux caserne:f:🚒 commissariat:m:👮 usine:f:🏭 chantier:m:🚧 ferme:f:🚜 campagne:f:🌾 pays:m:🌍: monde:m:🌍 région:f:🗺️ frontière:f:🛂 capitale:f:🏙️ carrefour:m:🚦 feu:m:🚦 panneau:m:🪧 parking:m:🅿️'],
  ['transport', 4, 'voiture:f:🚗 auto:f:🚗 bus:m:🚌: car:m:🚌 train:m:🚆 métro:m:🚇 tramway:m:🚊 vélo:m:🚲 bicyclette:f:🚲 trottinette:f:🛴 moto:f:🏍️ scooter:m:🛵 camion:m:🚚 camionnette:f:🚐 tracteur:m:🚜 ambulance:f:🚑 taxi:m:🚕 bateau:m:⛵ voilier:m:⛵ navire:m:🚢 ferry:m:⛴️ avion:m:✈️ hélicoptère:m:🚁 fusée:f:🚀 montgolfière:f:🎈 roue:f:🛞 pneu:m:🛞 volant:m:🎡 moteur:m:⚙️ essence:f:⛽ casque:m:🪖 siège:m:💺 ceinture:f:🔗 passager:m:🧍 conducteur:m:🚗 voyage:m:🧳 trajet:m:🗺️ arrêt:m:🚏 quai:m:🚉 embouteillage:m:🚗'],

  // ─── Vêtements ─────────────────────────────────────────────────────────
  ['vêtement', 4, 'vêtement:m:👕 habit:m:👕 tee-shirt:m:👕 chemise:f:👔 pull:m:🧥 pullover:m:🧥 gilet:m:🧥 veste:f:🧥 manteau:m:🧥 blouson:m:🧥 anorak:m:🧥 pantalon:m:👖 jean:m:👖 short:m:🩳 jupe:f:👗 robe:f:👗 chaussette:f:🧦 chaussure:f:👟 basket:f:👟 botte:f:👢 sandale:f:👡 pantoufle:f:🥿 chausson:m:🥿 bonnet:m:🧢 casquette:f:🧢 chapeau:m:👒 écharpe:f:🧣 gant:m:🧤 moufle:f:🧤 maillot:m:🩱 pyjama:m:🛌 ceinture:f:👖 poche:f:👖 manche:f:👕 col:m:👔 bouton:m:🔘 fermeture:f:🤐 lacet:m:👟 uniforme:m:👔 costume:m:🤵 déguisement:m:🦸 masque:m:🎭 bijou:m:💍 collier:m:📿 bague:f:💍 bracelet:m:📿 boucle d\'oreille:f:💎 sac à main:m:👜'],

  // ─── Jeux, sports, loisirs ─────────────────────────────────────────────
  ['jeu', 5, 'jeu:m:🎮:jeux jouet:m:🧸 poupée:f:🪆 peluche:f:🧸 nounours:m:🧸 doudou:m:🧸 ballon:m:⚽ balle:f:⚾ bille:f:🔵 toupie:f:🌀 cube:m:🧊 puzzle:m:🧩 carte:f:🃏 dé:m:🎲 jeu de société:m:🎲 console:f:🎮 manette:f:🎮 tour:f:🏰 cabane:f:🛖 balançoire:f:🛝 toboggan:m:🛝 trampoline:m:🤸 corde à sauter:f:🪢 cerf-volant:m:🪁 château de sable:m:🏖️ seau:m:🪣 pelle:f:🪏 déguisement:m:🎭 bulle:f:🫧 tour de magie:m:✨'],
  ['sport', 4, 'sport:m:⚽ football:m:⚽ foot:m:⚽ basket:m:🏀 tennis:m:🎾: rugby:m:🏉 handball:m:🤾 volley:m:🏐 natation:f:🏊 danse:f:💃 gymnastique:f:🤸 judo:m:🥋 karaté:m:🥋 escalade:f:🧗 athlétisme:m:🏃 course:f:🏃 saut:m:🦘 vélo:m:🚲 ski:m:🎿 patin:m:⛸️ patinage:m:⛸️ équitation:f:🏇 randonnée:f:🥾 match:m:🏆 équipe:f:👥 joueur:m:🏃 entraîneur:m:📋 entraînement:m:💪 arbitre:m:🟨 but:m:🥅 point:m:💯 score:m:🔢 victoire:f:🏆 défaite:f:😞 médaille:f:🏅 coupe:f:🏆 champion:m:🏆 tournoi:m:🏆 gymnase:m:🤸 terrain:m:🏟️ piste:f:🏁 filet:m:🥅 raquette:f:🎾 maillot:m:👕'],
  ['musique', 3, 'musique:f:🎵 chanson:f:🎶 chant:m:🎤 note:f:🎵 instrument:m:🎻 piano:m:🎹 guitare:f:🎸 violon:m:🎻 flûte:f:🪈 tambour:m:🥁 batterie:f:🥁 trompette:f:🎺 harmonica:m:🪗 xylophone:m:🎼 orchestre:m:🎻 concert:m:🎤 rythme:m:🥁 mélodie:f:🎶 danse:f:💃 spectacle:m:🎭 scène:f:🎭 micro:m:🎤 haut-parleur:m:🔊'],
  ['art', 3, 'art:m:🎨 dessin:m:✏️ peinture:f:🎨 pinceau:m:🖌️ couleur:f:🌈 crayon de couleur:m:🖍️ feutre:m:🖍️ palette:f:🎨 toile:f:🖼️ sculpture:f:🗿 poterie:f:🏺 argile:f:🏺 pâte à modeler:f:🎨 bricolage:m:✂️ découpage:m:✂️ collage:m:🩹 origami:m:🗾 œuvre:f:🖼️ artiste:mf:🧑‍🎨 exposition:f:🖼️ modèle:m:🖼️ film:m:🎬 dessin animé:m:📺 bande dessinée:f:📚 BD:f:📚: série:f:📺 conte:m:📖 roman:m:📕 poésie:f:📜 fable:f:🦊 légende:f:🐉 aventure:f:🗺️ personnage:m:🧙 héros:m:🦸:'],

  // ─── Abstrait & vie quotidienne ────────────────────────────────────────
  ['idée', 4, 'idée:f:💡 pensée:f:💭 rêve:m:💭 souvenir:m:🧠 projet:m:📋 plan:m:🗺️ but:m:🎯 raison:f:🤔 cause:f:🤔 problème:m:❓ solution:f:💡 choix:m:🤷: décision:f:⚖️ avis:m:💬: exemple:f:👉 façon:f:🤷 manière:f:🤷 moyen:m:🛠️ chance:f:🍀 hasard:m:🎲 surprise:f:🎁 aventure:f:🗺️ danger:m:⚠️ risque:m:⚠️ sécurité:f:🦺 vérité:f:✅ mensonge:m:🤥 réalité:f:👁️ imagination:f:🌈 magie:f:✨ mystère:m:🔍 secret:m:🤫 règle:f:📏 loi:f:⚖️ droit:m:⚖️ liberté:f:🕊️ paix:f:🕊️ guerre:f:⚔️ vie:f:🌱 mort:f:🪦 âge:m:🎂 début:m:▶️ fin:f:⏹️ suite:f:➡️ partie:f:🧩 groupe:m:👥 liste:f:📋 travail:m:💼:travaux jeu:m:🎮:jeux besoin:m:🙏 habitude:f:🔁 tour:m:🔄 fois:f:🔢: bruit:m:🔊 son:m:🔊 silence:m:🤫 odeur:f:👃 goût:m:👅 toucher:m:✋ vue:f:👁️ force:f:💪 vitesse:f:💨 poids:m:⚖️: taille:f:📏 hauteur:f:📏 longueur:f:📏 largeur:f:📏 espace:m:📐 endroit:m:📍 lieu:m:📍 place:f:📍 côté:m:↔️ droite:f:➡️ gauche:f:⬅️ haut:m:⬆️ bas:m:⬇️ intérieur:m:📥 extérieur:m:📤 dehors:m:🌳 dedans:m:🏠 centre:m:🎯 coin:m:📐 chemin:m:🛤️ direction:f:🧭 distance:f:📏'],
  ['sortie', 3, 'sortie:f:🚪 promenade:f:🚶 balade:f:🚶 visite:f:👀 invitation:f:💌 fête:f:🎉 anniversaire:m:🎂 cadeau:m:🎁 bougie:f:🕯️ surprise:f:🎊 vacances:f:🏖️ camping:m:⛺ colonie:f:⛺ centre aéré:m:🎨 séjour:m:🏨 excursion:f:🚌 pique-nique:m:🧺 kermesse:f:🎪 cirque:m:🎪 fête foraine:f:🎡 manège:f:🎠 parc d\'attractions:m:🎢 feu d\'artifice:m:🎆 défilé:m:🎺'],
];
